version: '2'
services:
  db-prod:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - odoo-network  # Attach db-prod to the custom network

  odoo18-prod:
    image: odoo:18
    user: root
    depends_on:
      - db-prod
    tty: true
    command: --
    environment:
      - HOST=db-prod
      - USER=odoo
      - PASSWORD=odoo18@2024
      - PIP_BREAK_SYSTEM_PACKAGES=1
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    networks:
      - odoo-network  # Attach odoo-prod to the custom network

networks:
  odoo-network:
    driver: bridge  # Define odoo-network explicitly as a bridge network
    name: odoo-network  # Ensure Docker uses this network name explicitly
